# 中文语言包
!insertmacro MUI_LANGUAGE "SimpChinese"

# 自定义中文字符串
LangString INSTALL_TYPE_TITLE ${LANG_SIMPCHINESE} "安装类型"
LangString INSTALL_TYPE_SUBTITLE ${LANG_SIMPCHINESE} "选择安装方式"
LangString INSTALL_TYPE_STANDARD ${LANG_SIMPCHINESE} "标准安装（推荐）"
LangString INSTALL_TYPE_STANDARD_DESC ${LANG_SIMPCHINESE} "安装 PromptMate 到默认位置"
LangString INSTALL_TYPE_CUSTOM ${LANG_SIMPCHINESE} "自定义安装"
LangString INSTALL_TYPE_CUSTOM_DESC ${LANG_SIMPCHINESE} "选择安装位置和组件"
LangString INSTALL_TYPE_PORTABLE ${LANG_SIMPCHINESE} "便携安装"
LangString INSTALL_TYPE_PORTABLE_DESC ${LANG_SIMPCHINESE} "不注册到系统，可在任意位置运行"

LangString DATA_DIR_TITLE ${LANG_SIMPCHINESE} "数据目录设置"
LangString DATA_DIR_SUBTITLE ${LANG_SIMPCHINESE} "选择用户数据保存位置"
LangString DATA_DIR_DEFAULT ${LANG_SIMPCHINESE} "使用默认位置"
LangString DATA_DIR_CUSTOM ${LANG_SIMPCHINESE} "自定义位置"
LangString DATA_DIR_BROWSE ${LANG_SIMPCHINESE} "浏览..."
LangString DATA_DIR_NOTE ${LANG_SIMPCHINESE} "注意：选择自定义目录后，请确保该位置有足够的磁盘空间。数据目录将用于存储您的提示词、设置和其他应用数据。"

LangString COMPONENTS_TITLE ${LANG_SIMPCHINESE} "选择组件"
LangString COMPONENTS_SUBTITLE ${LANG_SIMPCHINESE} "选择要安装的组件"
LangString COMPONENT_MAIN ${LANG_SIMPCHINESE} "PromptMate 主程序"
LangString COMPONENT_MAIN_DESC ${LANG_SIMPCHINESE} "PromptMate 核心程序文件"
LangString COMPONENT_DESKTOP ${LANG_SIMPCHINESE} "桌面快捷方式"
LangString COMPONENT_DESKTOP_DESC ${LANG_SIMPCHINESE} "在桌面创建快捷方式"
LangString COMPONENT_STARTMENU ${LANG_SIMPCHINESE} "开始菜单快捷方式"
LangString COMPONENT_STARTMENU_DESC ${LANG_SIMPCHINESE} "在开始菜单创建快捷方式"
LangString COMPONENT_AUTOSTART ${LANG_SIMPCHINESE} "开机自启动"
LangString COMPONENT_AUTOSTART_DESC ${LANG_SIMPCHINESE} "系统启动时自动运行 PromptMate"

LangString FINISH_TITLE ${LANG_SIMPCHINESE} "安装完成"
LangString FINISH_SUBTITLE ${LANG_SIMPCHINESE} "PromptMate 已成功安装"
LangString FINISH_RUN ${LANG_SIMPCHINESE} "立即运行 PromptMate"
LangString FINISH_README ${LANG_SIMPCHINESE} "查看使用说明"
LangString FINISH_WEBSITE ${LANG_SIMPCHINESE} "访问官方网站"

LangString UPDATE_TITLE ${LANG_SIMPCHINESE} "更新检测"
LangString UPDATE_FOUND ${LANG_SIMPCHINESE} "检测到 PromptMate 已安装。是否要更新到新版本？"
LangString UPDATE_KEEP_DATA ${LANG_SIMPCHINESE} "更新过程中将保留您的所有数据。"
LangString UPDATE_BACKUP ${LANG_SIMPCHINESE} "建议在更新前备份重要数据。"

LangString UNINSTALL_TITLE ${LANG_SIMPCHINESE} "卸载确认"
LangString UNINSTALL_QUESTION ${LANG_SIMPCHINESE} "是否同时删除所有用户数据？"
LangString UNINSTALL_KEEP_DATA ${LANG_SIMPCHINESE} "选择"否"将保留您的提示词和设置。"
LangString UNINSTALL_DELETE_DATA ${LANG_SIMPCHINESE} "选择"是"将删除所有用户数据。"










