import {
  Star,
  StarOff,
  Copy,
  Pencil,
  Edit,
  Trash,
  MoreVertical,
  Plus,
  Check,
  X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Menu,
  Search,
  FileText,
  Settings,
  Palette,
  Maximize,
  Minimize,
  Cpu,
  SunMedium,
  Moon,
  PanelLeft,
  FolderPlus,
  FolderOpen,
  Folder,
  Layout,
  Gift,
  Upload,
  Download,
  Save,
  FileJson,
  AlertCircle,
  AlertTriangle,
  FileUp,
  FileDown,
  File,
  Pin,
  PinOff,
  Info,
  RefreshCw,
  RotateCcw,
  Github,
  Loader,
  MoveVertical,
  Image,
  History,
  GitCompare,
  GitBranch,
  Workflow,
  Play,
  Pause,
  Square,
  SkipForward,
  Circle,
  Heart,
  Filter,
  MoreHorizontal,
  ArrowLeft,
  Zap,
  FileCode,
  Variable,
  Clipboard,
  ZoomIn,
  ZoomOut,
  Cloud,
  Database,
  Archive,
  Globe,
  HardDrive,
  Server,
  Puzzle,
  Lightbulb,
  User,
  Refresh
} from "lucide-react";

export const Icons = {
  star: Star,
  starOff: StarOff,
  starFilled: Star,
  copy: Copy,
  pencil: Pencil,
  edit: Edit,
  trash: Trash,
  moreVertical: MoreVertical,
  plus: Plus,
  check: Check,
  x: X,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  menu: Menu,
  search: Search,
  fileText: FileText,
  settings: Settings,
  palette: Palette,
  maximize: Maximize,
  minimize: Minimize,
  sun: SunMedium,
  moon: Moon,
  panelLeft: PanelLeft,
  folderPlus: FolderPlus,
  folderOpen: FolderOpen,
  folder: Folder,
  layout: Layout,
  gift: Gift,
  upload: Upload,
  download: Download,
  save: Save,
  fileJson: FileJson,
  fileExport: FileDown,
  fileUp: FileUp,
  file: File,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  pin: Pin,
  pinOff: PinOff,
  info: Info,
  refresh: RefreshCw,
  rotateCcw: RotateCcw,
  github: Github,
  loader: Loader,
  bot: AlertCircle,
  moveVertical: MoveVertical,
  image: Image,
  history: History,
  gitCompare: GitCompare,
  gitBranch: GitBranch,
  workflow: Workflow,
  play: Play,
  pause: Pause,
  stop: Square,
  square: Square,
  skip: SkipForward,
  circle: Circle,
  heart: Heart,
  filter: Filter,
  moreHorizontal: MoreHorizontal,
  arrowLeft: ArrowLeft,
  zap: Zap,
  template: FileCode,
  variable: Variable,
  clipboard: Clipboard,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  cpu: Cpu,
  cloud: Cloud,
  database: Database,
  archive: Archive,
  google: Globe,
  dropbox: HardDrive,
  microsoft: Server,
  puzzle: Puzzle,
  lightbulb: Lightbulb,
  user: User
}; 